/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("Use this tool to set the installed operating\n"
              "systems to choose from at startup.");
gchar *s = N_("_Add...");
gchar *s = N_("_Delete");
gchar *s = N_("_Settings...");
gchar *s = N_("D_efault");
gchar *s = N_("Starting your computer");
gchar *s = N_("_Wait");
gchar *s = N_("_seconds before loading default kernel or OS");
gchar *s = N_("Settings");
gchar *s = N_("Use this dialog to add new kernel or\n"
              "operating system to your computer.");
gchar *s = N_("Boot _type:");
gchar *s = N_("_Name:");
gchar *s = N_("Settings");
gchar *s = N_("N_ame:");
gchar *s = N_("_Image:");
gchar *s = N_("_Device:");
gchar *s = N_("Optional");
gchar *s = N_("_Root:");
gchar *s = N_("_Append:");
