/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window1");
gchar *s = N_("This is going to be Boot admin tool.\n"
              "It's going to be cool thing. Can someone\n"
              "write better text here?");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Settings");
gchar *s = N_("Global stuff");
gchar *s = N_("Timeout");
gchar *s = N_("Seconds");
