/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Name Resolution Administration");
gchar *s = N_("Scanning your system configuration.\n"
              "\n"
              "This could take a few seconds; please hold on in the meantime.");
