/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Disks Administration");
gchar *s = N_("Device");
gchar *s = N_("Detected");
gchar *s = N_("Listed");
gchar *s = N_("Mounted");
gchar *s = N_("Size");
gchar *s = N_("Bootable");
gchar *s = N_("Check");
gchar *s = N_("Mount point");
gchar *s = N_("Partition");
gchar *s = N_("Add an unlisted import");
gchar *s = N_("Add partition");
gchar *s = N_("Mount this partition");
gchar *s = N_("Open settings dialog for selected import");
gchar *s = N_("Settings");
gchar *s = N_("Remember details of this partition");
gchar *s = N_("Disks & partitions");
gchar *s = N_("Partition Settings");
gchar *s = N_("Type:");
gchar *s = N_("Device:");
gchar *s = N_("Mount point:");
gchar *s = N_("Automatic (detect when mounting)\n"
              "Ext2 (Linux)\n"
              "FAT (DOS)\n"
              "VFAT (Windows 95 and newer)\n"
              "FAT32 (Windows 98 and newer)\n"
              "NTFS (Windows NT & 2000)\n"
              "");
gchar *s = N_("Choose a mount point");
gchar *s = N_("Check for errors on startup");
