/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window2");
gchar *s = N_("Monitor information (from X server)");
gchar *s = N_("Vendor:");
gchar *s = N_("Model:");
gchar *s = N_("<unknown>");
gchar *s = N_("<unknown>");
gchar *s = N_("Up");
gchar *s = N_("Left");
gchar *s = N_("Right");
gchar *s = N_("Down");
gchar *s = N_("Taller");
gchar *s = N_("Narrower");
gchar *s = N_("Wider");
gchar *s = N_("Shorter");
gchar *s = N_("Restart X");
gchar *s = N_("Resolution");
