/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("window2");
gchar *s = N_("Up");
gchar *s = N_("Left");
gchar *s = N_("Right");
gchar *s = N_("Down");
gchar *s = N_("Taller");
gchar *s = N_("Narrower");
gchar *s = N_("Wider");
gchar *s = N_("Shorter");
gchar *s = N_("Restart X");
gchar *s = N_("Resolution:");
gchar *s = N_("Colors:");
gchar *s = N_("640x480");
gchar *s = N_("800x600");
gchar *s = N_("1024x768");
gchar *s = N_("1280x1024");
gchar *s = N_("Refresh rate:");
gchar *s = N_("Shift my display:");
gchar *s = N_("Left");
gchar *s = N_("Right");
gchar *s = N_("Up");
gchar *s = N_("Down");
gchar *s = N_("Stretch my display:");
gchar *s = N_("Narrower");
gchar *s = N_("Wider");
gchar *s = N_("Shorter");
gchar *s = N_("Taller");
gchar *s = N_("_Restore settings");
gchar *s = N_("window2");
gchar *s = N_("Use this tool to configure your monitor. balh balhan837498 q29487 1 98374 ");
gchar *s = N_("Monitor information");
gchar *s = N_("Vendor:");
gchar *s = N_("Model:");
gchar *s = N_("<unknown>");
gchar *s = N_("<unknown>");
gchar *s = N_("Resolution");
gchar *s = N_("label49");
gchar *s = N_("Test current setting");
gchar *s = N_("Colors");
gchar *s = N_("label50");
gchar *s = N_("Appearance");
