/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Select the fonts you want to install.");
gchar *s = N_("Font family");
gchar *s = N_("Style");
gchar *s = N_("Font size:");
gchar *s = N_("Add font...");
gchar *s = N_("Delete font");
gchar *s = N_("Preview");
