/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Internet Sharing --Advanced Mode");
gchar *s = N_("The internet sharing tool allows you to share your internet conection with other computers on the network.");
gchar *s = N_("Internet Sharing");
gchar *s = N_("Enable");
gchar *s = N_("Enable :");
gchar *s = N_("IP Forwarding");
gchar *s = N_("DHCP");
gchar *s = N_("Firewall");
gchar *s = N_("Web Cache (squid)");
gchar *s = N_("Banner Removal (Junkbuster)");
