/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Rollback-location-management-mockup");
gchar *s = N_("Use this tool to manage all the different locations where you could possibly want to use your stinking laptop.");
gchar *s = N_("Choose Location");
gchar *s = N_("Current:");
gchar *s = N_("Edit Location");
gchar *s = N_("Edit:");
gchar *s = N_("                           ");
gchar *s = N_("\n"
              "");
gchar *s = N_("_Settings...");
gchar *s = N_("_Help");
gchar *s = N_("Location Management");
gchar *s = N_("New Location");
gchar *s = N_("New Location");
gchar *s = N_("Name:");
gchar *s = N_("Locations");
gchar *s = N_("Edit Date/Time");
gchar *s = N_("Location:");
gchar *s = N_("Boston Office");
gchar *s = N_("Date");
gchar *s = N_("Time");
gchar *s = N_(":");
gchar *s = N_(":");
gchar *s = N_("AM");
gchar *s = N_("PM");
gchar *s = N_("Time zone");
gchar *s = N_("(unconfigured)");
gchar *s = N_("Set time zone...");
gchar *s = N_("Time server");
gchar *s = N_("Keep clock synchronized with selected servers");
gchar *s = N_("Select servers...");
gchar *s = N_("Date/time");
gchar *s = N_("Date/Time ");
gchar *s = N_("Please select the current date and time. You can also specify a time zone and a time server.");
gchar *s = N_("Location");
gchar *s = N_("Name:");
gchar *s = N_("Boston Office");
gchar *s = N_("Helsinki Office");
gchar *s = N_("Mexico CIty ");
gchar *s = N_("Boston Office");
gchar *s = N_("Date");
gchar *s = N_("Time");
gchar *s = N_(":");
gchar *s = N_(":");
gchar *s = N_("AM");
gchar *s = N_("PM");
gchar *s = N_("Time zone");
gchar *s = N_("(unconfigured)");
gchar *s = N_("Set time zone...");
gchar *s = N_("Time server");
gchar *s = N_("Keep clock synchronized with selected servers");
gchar *s = N_("Select servers...");
gchar *s = N_("Date/time");
gchar *s = N_("Rename Location");
gchar *s = N_("Rename");
gchar *s = N_("New name:");
gchar *s = N_("Locations");
gchar *s = N_("Copy Location");
gchar *s = N_("Copy");
gchar *s = N_("New Name:");
gchar *s = N_("Locations");
