/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Memory administration");
gchar *s = N_("Swap Memory:");
gchar *s = N_("Physical Memory:");
gchar *s = N_("These are the swap areas available:");
gchar *s = N_("Enabled");
gchar *s = N_("Device");
gchar *s = N_("Priority");
gchar *s = N_("Size");
gchar *s = N_("Create...");
gchar *s = N_("Remove");
gchar *s = N_("Settings...");
gchar *s = N_("Available partitions:");
gchar *s = N_("Device");
gchar *s = N_("Size");
gchar *s = N_("Path:");
gchar *s = N_("Size:");
gchar *s = N_("Swap Partition\n"
              "Swap File\n"
              "");
gchar *s = N_("Megabytes");
gchar *s = N_("Enable this swap space");
gchar *s = N_("Use non-default priority:");
gchar *s = N_("Browse...");
gchar *s = N_("Swap device");
gchar *s = N_("Enable this swap space");
gchar *s = N_("Use non-default priority");
gchar *s = N_("Size:");
gchar *s = N_("Mb");
gchar *s = N_("Select  Swap File");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
