/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Available partitions:");
gchar *s = N_("Device");
gchar *s = N_("Size");
gchar *s = N_("Select  Swap File");
gchar *s = N_("OK");
gchar *s = N_("Cancel");
gchar *s = N_("Swap Settings");
gchar *s = N_("Device:");
gchar *s = N_("Enabled");
gchar *s = N_("Settings");
gchar *s = N_("MB");
gchar *s = N_("Size:");
gchar *s = N_("Priority:");
gchar *s = N_("New Swap Device");
gchar *s = N_("Swap type:");
gchar *s = N_("partition");
gchar *s = N_("file");
gchar *s = N_("Enabled");
gchar *s = N_("Settings");
gchar *s = N_("MB");
gchar *s = N_("Browse...");
gchar *s = N_("Path:");
gchar *s = N_("Size:");
gchar *s = N_("Priority:");
gchar *s = N_("window1");
gchar *s = N_("Available swap areas");
gchar *s = N_("Enabled");
gchar *s = N_("Device");
gchar *s = N_("Priority");
gchar *s = N_("Size");
gchar *s = N_("_Add");
gchar *s = N_("Settings");
gchar *s = N_("window1");
gchar *s = N_("Swap memory:");
gchar *s = N_("Physical memory:");
gchar *s = N_("Available swap areas");
gchar *s = N_("Enabled");
gchar *s = N_("Device");
gchar *s = N_("Priority");
gchar *s = N_("Size");
gchar *s = N_("_Add");
gchar *s = N_("_Remove");
gchar *s = N_("_Settings");
