/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Aliases Settings");
gchar *s = N_("IP address:");
gchar *s = N_("Aliases");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Existing:");
gchar *s = N_("New:");
gchar *s = N_("Let the computer know its name, function and network surroundings.");
gchar *s = N_("Host");
gchar *s = N_("Host name:");
gchar *s = N_("Reverse:");
gchar *s = N_("<unknown>");
gchar *s = N_("Domain");
gchar *s = N_("Domain:");
gchar *s = N_("Reverse:");
gchar *s = N_("<unknown>");
gchar *s = N_("Workgroup:");
gchar *s = N_("Description:");
gchar *s = N_("Identification");
gchar *s = N_("Domain Name Service (DNS)");
gchar *s = N_("New server:");
gchar *s = N_("Existing:");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Use WINS server:");
gchar *s = N_("Servers");
gchar *s = N_("Domain Lookup Order");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_(" Move Up");
gchar *s = N_("Move Down");
gchar *s = N_("New domain:");
gchar *s = N_("Existing:");
gchar *s = N_("Search Domains");
gchar *s = N_("Assign aliases to IP addresses that may not be registered in the DNS or WINS servers, or to override or set new names for commonly used IP addresses. ");
gchar *s = N_("IP address");
gchar *s = N_(" Names");
gchar *s = N_("New Alias");
gchar *s = N_("Delete");
gchar *s = N_("Settings for the selected alias");
gchar *s = N_("Change the alias' IP address or its corresponding names.");
gchar *s = N_("Settings");
gchar *s = N_("Aliases");
