/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Name Resolution Administration");
gchar *s = N_("Host");
gchar *s = N_("Host name:");
gchar *s = N_("Reverse:");
gchar *s = N_("<unknown>");
gchar *s = N_("Domain");
gchar *s = N_("Domain:");
gchar *s = N_("Reverse:");
gchar *s = N_("<unknown>");
gchar *s = N_("Workgroup:");
gchar *s = N_("Description:");
gchar *s = N_("Identification");
gchar *s = N_("Domain Name Service (DNS)");
gchar *s = N_("Add");
gchar *s = N_(".");
gchar *s = N_(".");
gchar *s = N_(".");
gchar *s = N_("Remove");
gchar *s = N_("Use WINS server:");
gchar *s = N_(".");
gchar *s = N_(".");
gchar *s = N_(".");
gchar *s = N_("Name Resolution");
gchar *s = N_("Add");
gchar *s = N_("Remove");
gchar *s = N_("Search Domains");
gchar *s = N_("IP address");
gchar *s = N_("Aliases");
gchar *s = N_(".");
gchar *s = N_(".");
gchar *s = N_(".");
gchar *s = N_("Add IP");
gchar *s = N_("Remove IP");
gchar *s = N_("Set aliases");
gchar *s = N_("Static names");
gchar *s = N_(" Advanced >> ");
