/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Networking Settings");
gchar *s = N_("How this computer is identified.");
gchar *s = N_("Host name:");
gchar *s = N_("Enable windows networking (Samba)");
gchar *s = N_("Windows Networking");
gchar *s = N_("Description:");
gchar *s = N_("Workgroup:");
gchar *s = N_("WINS server:");
gchar *s = N_("General");
gchar *s = N_("How other computers are accessed.");
gchar *s = N_("Device");
gchar *s = N_("Status");
gchar *s = N_("Description");
gchar *s = N_("Add...");
gchar *s = N_("Delete...");
gchar *s = N_("Configure...");
gchar *s = N_("Activate");
gchar *s = N_("Deactivate");
gchar *s = N_("Connections");
gchar *s = N_("How the names of other computers are found.");
gchar *s = N_("Domain:");
gchar *s = N_("DNS Servers:");
gchar *s = N_("Search Domains:");
gchar *s = N_("DNS");
gchar *s = N_("Aliases of other computers.");
gchar *s = N_("IP Address");
gchar *s = N_("Aliases");
gchar *s = N_("IP address:");
gchar *s = N_("Aliases:");
gchar *s = N_("Add");
gchar *s = N_("Delete");
gchar *s = N_("Hosts");
gchar *s = N_("New Connection Type");
gchar *s = N_("Select which type of connection you would like to add.");
gchar *s = N_("Modem (PPP)");
gchar *s = N_("Ethernet");
gchar *s = N_("Wavelan");
gchar *s = N_("Parallel Line");
gchar *s = N_("Connection Settings");
gchar *s = N_("Use the comment to identify the interface in the future. Activation management lets you set who and when will activate connections.");
gchar *s = N_("Connection");
gchar *s = N_("Device:");
gchar *s = N_("Comment:");
gchar *s = N_("Activation");
gchar *s = N_("Allow activation control for all users");
gchar *s = N_("Activate when the computer starts");
gchar *s = N_("General");
gchar *s = N_("How the IP address for this connection is determined");
gchar *s = N_("Configuration:");
gchar *s = N_("Manual");
gchar *s = N_("DHCP");
gchar *s = N_("BOOTP");
gchar *s = N_("Update DNS when this connection becomes active");
gchar *s = N_("IP address:");
gchar *s = N_("Subnet mask:");
gchar *s = N_("Gateway address:");
gchar *s = N_("IP Settings");
gchar *s = N_("Wireless networking settings.");
gchar *s = N_("Ad-Hoc mode");
gchar *s = N_("Ad-Hoc Settings");
gchar *s = N_("Session ID:");
gchar *s = N_("Frequency (GHz):");
gchar *s = N_("2.422");
gchar *s = N_("Channel:");
gchar *s = N_("WaveLAN");
gchar *s = N_("How to dial up to the internet.");
gchar *s = N_("Phone number:");
gchar *s = N_("User name:");
gchar *s = N_("Password:");
gchar *s = N_("Options");
gchar *s = N_("Restart if connection cuts or fails to start");
gchar *s = N_("Account");
gchar *s = N_("Advanced PPP connection tunning.");
gchar *s = N_("Modem port:");
gchar *s = N_("DNS Servers");
gchar *s = N_("Primary:");
gchar *s = N_("Secondary:");
gchar *s = N_("Set DNS servers manually");
gchar *s = N_("Start PPP as soon as modem connects");
gchar *s = N_("Set as default route");
gchar *s = N_("Pppd options:");
gchar *s = N_("Advanced");
gchar *s = N_("How the IP addresses for this connection are determined");
gchar *s = N_("Local IP:");
gchar *s = N_("Remote IP:");
gchar *s = N_("Use remote IP as default gateway");
gchar *s = N_("IP Settings");
gchar *s = N_("Add New Internet Connection");
gchar *s = N_("Create a new Internet Connection ");
gchar *s = N_("Welcome to the Internet Connection druid. \n"
              "\n"
              "This druid will help you to configure a new \n"
              "internet account. \n"
              "\n"
              "Before you begin, you must have a modem and\n"
              "an Internet Service Provider (ISP). Please ask your \n"
              "ISP for any information about your connection which\n"
              "you are lacking.\n"
              "\n"
              "Click the \"Next\" button to begin.");
gchar *s = N_("1. ISP phone number");
gchar *s = N_("First, please enter the phone number you use to connect to the internet. This number is provided by your ISP. ");
gchar *s = N_("Phone number:");
gchar *s = N_("To continue configuring your account, click \"Next\". To quit, click \"Cancel\".\n"
              "");
gchar *s = N_("Warning message goes here..\n"
              "");
gchar *s = N_("2. Username and password");
gchar *s = N_("Next, please enter the user name and password which were assigned to you by your ISP.");
gchar *s = N_("User name:");
gchar *s = N_("Password:");
gchar *s = N_("Password (confirm):");
gchar *s = N_("Warning message goes here..\n"
              "");
gchar *s = N_("To continue configuring your account, click \"Next\". To quit, click \"Cancel\".\n"
              "");
gchar *s = N_("3. Account name");
gchar *s = N_("Now, please give this account a name. This name will be used to identify the account.");
gchar *s = N_("Account name:");
gchar *s = N_("To continue configuring your account, click \"Next\". To quit, click \"Cancel\".\n"
              "");
gchar *s = N_("Warning message goes here..\n"
              "");
gchar *s = N_("Finished");
gchar *s = N_("Summary of new account data\n"
              "goes here, plus indications on\n"
              "how to proceed (go back, cancel\n"
              "or finish).");
gchar *s = N_("window1");
gchar *s = N_("Activation");
gchar *s = N_("Connection active");
gchar *s = N_("Activate when the computer starts");
gchar *s = N_("Allow activation control for all users");
