/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Networking Administration");
gchar *s = N_("Interface:");
gchar *s = N_("Gateway IP:");
gchar *s = N_("Netmask:");
gchar *s = N_("Host IP:");
gchar *s = N_("Use DHCP server");
gchar *s = N_("Enable automatically at boot");
gchar *s = N_("Primary networking");
gchar *s = N_(" More Options >> ");
