/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Printer Settings");
gchar *s = N_("Connection");
gchar *s = N_("_Name");
gchar *s = N_("_Hostname");
gchar *s = N_("_Remote Name");
gchar *s = N_("_Workgroup");
gchar *s = N_("_Username");
gchar *s = N_("_Password");
gchar *s = N_("P_ort Number");
gchar *s = N_("_Device Name");
gchar *s = N_("/dev/lp0 (LPT1)");
gchar *s = N_("/dev/lp1 (LPT2)");
gchar *s = N_("/dev/ttyS0 (COM1)");
gchar *s = N_("/dev/ttyS1 (COM2)");
gchar *s = N_("/dev/ttyS2 (COM3)");
gchar *s = N_("/dev/ttyS3 (COM4)");
gchar *s = N_("Driver");
gchar *s = N_("R_esolution");
gchar *s = N_("P_aper Size");
gchar *s = N_("_Color Depth");
gchar *s = N_("300x300");
gchar *s = N_("400x400");
gchar *s = N_("600x600");
gchar *s = N_("1200x600");
gchar *s = N_("1200x1200");
gchar *s = N_("Letter");
gchar *s = N_("Legal");
gchar *s = N_("A4");
gchar *s = N_("A3");
gchar *s = N_("16 colors");
gchar *s = N_("256 colors");
gchar *s = N_("High Color");
gchar *s = N_("True Color");
gchar *s = N_("Options");
gchar *s = N_("_Explicitly Eject Last Page");
gchar *s = N_("Convert _Linefeeds");
gchar *s = N_("_Fast Text Printing");
gchar *s = N_("Document Pages per Sheet");
gchar *s = N_("1\t");
gchar *s = N_("2");
gchar *s = N_("4");
gchar *s = N_("8");
gchar *s = N_("window1");
gchar *s = N_("This is the list of the configured printers available on the system. Create new printers or edit existing printer settings with this dialog.");
gchar *s = N_("Add Printer...");
gchar *s = N_("Settings...");
gchar *s = N_("Delete");
gchar *s = N_("Add a New Printer");
gchar *s = N_("Select the type of printer to add:");
gchar *s = N_("_Local Printer");
gchar *s = N_("Remote _Windows (SMB) printer");
gchar *s = N_("Network UNIX (_lpd) Printer");
gchar *s = N_("Novell _Netware (NCP) Printer");
gchar *s = N_("_Direct Network Printer");
