/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("User Settings");
gchar *s = N_("Remote _Windows (SMB) printer");
gchar *s = N_("_Local Printer");
gchar *s = N_("Novel _Netware (NCP) Printer");
gchar *s = N_("Remote UNIX (_lpd) printer");
gchar *s = N_("_Direct to port printer");
gchar *s = N_("Dummy Printer");
gchar *s = N_("S_erver");
gchar *s = N_("S_pool");
gchar *s = N_("_User");
gchar *s = N_("_Password");
gchar *s = N_("_Workgroup");
gchar *s = N_("D_evice");
gchar *s = N_("_Filter");
gchar *s = N_("Select");
gchar *s = N_("window1");
gchar *s = N_("This is the list of the configured printers available on the system. Create new printers or edit existing printer settings with this dialog.");
gchar *s = N_("Add Printer...");
gchar *s = N_("Settings...");
gchar *s = N_("Delete");
