/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("User Settings");
gchar *s = N_("Basic settings");
gchar *s = N_("User name:");
gchar *s = N_("Full Name:");
gchar *s = N_("Advanced settings");
gchar *s = N_("User ID:");
gchar *s = N_("Home directory:");
gchar *s = N_("Shell:");
gchar *s = N_("Basic");
gchar *s = N_("Main group:");
gchar *s = N_("Groups");
gchar *s = N_("Available Groups");
gchar *s = N_("User's Groups");
gchar *s = N_("Add ->");
gchar *s = N_("Remove <-");
gchar *s = N_(" Primary Group ");
gchar *s = N_("label27");
gchar *s = N_("label26");
gchar *s = N_("Groups");
gchar *s = N_("Change Password");
gchar *s = N_("Change Password");
gchar *s = N_("  Generate a random password  ");
gchar *s = N_("Check password quality");
gchar *s = N_("Optional Settings");
gchar *s = N_("Maximum days a password may be used:");
gchar *s = N_("Minimum days between password changes:");
gchar *s = N_("Days between warning and password expiration:");
gchar *s = N_("Passwords");
gchar *s = N_("window1");
gchar *s = N_("This is the list of the configured printers available on the system. Create new printers or edit existing printer settings with this dialog.");
gchar *s = N_("Add Printer...");
gchar *s = N_("Settings...");
gchar *s = N_("Delete");
