/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("simple mode--main window");
gchar *s = N_("Imports are directories which reside in other computers and are accessible to you through the network.");
gchar *s = N_("Host");
gchar *s = N_("Path");
gchar *s = N_("Mount Point");
gchar *s = N_("Mounted");
gchar *s = N_("\n"
              "");
gchar *s = N_("Add...");
gchar *s = N_("Settings...");
gchar *s = N_("Delete");
gchar *s = N_("Imports");
gchar *s = N_("Exports are used to share directories on your computer with other computers over the network. ");
gchar *s = N_("Name");
gchar *s = N_("Path");
gchar *s = N_("Clients");
gchar *s = N_("Writable");
gchar *s = N_("\n"
              "");
gchar *s = N_("Add...");
gchar *s = N_("Settings...");
gchar *s = N_("Delete");
gchar *s = N_("Exports");
gchar *s = N_("advanced mode--main window");
gchar *s = N_("Imports are directories which reside in other computers and are accessible to you through the network.");
gchar *s = N_("\n"
              "");
gchar *s = N_("_Add...");
gchar *s = N_("_Settings...");
gchar *s = N_("_Delete");
gchar *s = N_("_Mount");
gchar *s = N_("_Scan");
gchar *s = N_("Imports");
gchar *s = N_("Exports are used to share directories on your computer with other computers over the network. ");
gchar *s = N_("\n"
              "");
gchar *s = N_("_Add...");
gchar *s = N_("_Settings...");
gchar *s = N_("_Delete");
gchar *s = N_("_Enable");
gchar *s = N_("Exports");
gchar *s = N_("export settings--NFS options");
gchar *s = N_("Use this dialog to create a new export, or to edit the settings of an existing export.");
gchar *s = N_("Export type:");
gchar *s = N_("Enabled");
gchar *s = N_("NFS\n"
              "Samba\n"
              "");
gchar *s = N_("Export");
gchar *s = N_("Name:");
gchar *s = N_("Path:");
gchar *s = N_("Comment:");
gchar *s = N_("Access control");
gchar *s = N_("Restrict access to this share to specific clients");
gchar *s = N_(" Edit clients... ");
gchar *s = N_("export settings--Samba options");
gchar *s = N_("Use this dialog to create a new export, or to edit the settings of an existing export.");
gchar *s = N_("Export type:");
gchar *s = N_("Enabled");
gchar *s = N_("NFS\n"
              "Samba\n"
              "");
gchar *s = N_("Export");
gchar *s = N_("Name:");
gchar *s = N_("Path:");
gchar *s = N_("Comment:");
gchar *s = N_("Access control");
gchar *s = N_("Browseable");
gchar *s = N_("Writable");
gchar *s = N_("Public");
gchar *s = N_("Access control");
gchar *s = N_("Restrict access to this share to specific clients");
gchar *s = N_(" Edit clients... ");
gchar *s = N_("add/edit clients");
gchar *s = N_("Use this dialog to define the client patterns which determine who has access to your NFS share. Client patterns are typically of the form \"10.10.10.*\" or \" *.gnome.org\".  ");
gchar *s = N_("Client");
gchar *s = N_("Pattern:");
gchar *s = N_("Allow writing");
gchar *s = N_("Add");
gchar *s = N_("Update");
gchar *s = N_("Delete");
gchar *s = N_("Import Settings--NFS Options");
gchar *s = N_("Use this dialog to create a new import, or to edit the settings of an existing import.");
gchar *s = N_("Import type:");
gchar *s = N_("NFS\n"
              "Samba\n"
              "");
gchar *s = N_("Mounted");
gchar *s = N_("Import");
gchar *s = N_("Host:");
gchar *s = N_("Path:");
gchar *s = N_("Mounting options");
gchar *s = N_("Mount point:");
gchar *s = N_("Do not remount this share after computer reboots");
gchar *s = N_("Import Settings--Samba Options (Obsolete)");
gchar *s = N_("Use this dialog to create a new import, or to edit the settings of an existing import.");
gchar *s = N_("Import type:");
gchar *s = N_("Samba\n"
              "NFS\n"
              "");
gchar *s = N_("Mounted");
gchar *s = N_("Import");
gchar *s = N_("Host:");
gchar *s = N_("Path:");
gchar *s = N_("Username:");
gchar *s = N_("Password:");
gchar *s = N_("Mounting Options");
gchar *s = N_("Mount point:");
gchar *s = N_("Do not remount this share after computer reboots");
gchar *s = N_("Import Settings");
gchar *s = N_("Use this dialog to create a new import, or to edit the settings of an existing import.");
gchar *s = N_("Import _type:");
gchar *s = N_("Samba\n"
              "NFS\n"
              "");
gchar *s = N_("_Mounted");
gchar *s = N_("Import");
gchar *s = N_("_Host:");
gchar *s = N_("_Path:");
gchar *s = N_("Pass_word:");
gchar *s = N_("_Username:");
gchar *s = N_("Mounting options");
gchar *s = N_("If the mount point does not exist, it will be created.");
gchar *s = N_("Mount p_oint:");
gchar *s = N_("Do not _remount this share after computer reboots");
gchar *s = N_("Export Settings");
gchar *s = N_("Use this dialog to create a new export, or to edit the settings of an existing export.");
gchar *s = N_("Export _type:");
gchar *s = N_("Enabled");
gchar *s = N_("Samba\n"
              "NFS\n"
              "");
gchar *s = N_("Export");
gchar *s = N_("_Name:");
gchar *s = N_("_Path:");
gchar *s = N_("_Comment:");
gchar *s = N_("Access control");
gchar *s = N_("_Browseable");
gchar *s = N_("_Writable");
gchar *s = N_("P_ublic");
gchar *s = N_("Access control");
gchar *s = N_("_Restrict access to this share to specific clients");
gchar *s = N_(" _Edit clients... ");
gchar *s = N_("Export Clients");
gchar *s = N_("Use this dialog to define the client patterns which determine who has access to your NFS share. Client patterns are typically of the form \"10.10.10.*\" or \" *.gnome.org\".  ");
gchar *s = N_("Client");
gchar *s = N_("Pattern:");
gchar *s = N_("Allow writing");
gchar *s = N_("Add");
gchar *s = N_("Update");
gchar *s = N_("Delete");
