/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Date/Time ");
gchar *s = N_("Please select the current date and time. You can also specify a time zone and a time server.");
gchar *s = N_("Date");
gchar *s = N_("Time");
gchar *s = N_("Time zone");
gchar *s = N_("(unconfigured)");
gchar *s = N_("Set time _zone...");
gchar *s = N_("Time server");
gchar *s = N_("_Keep clock synchronized with selected servers");
gchar *s = N_("Select _servers...");
gchar *s = N_("Date/time");
gchar *s = N_("Time zone");
gchar *s = N_("Select a time zone by clicking on \n"
              "one of the dots on the map.");
gchar *s = N_("Time Zones");
gchar *s = N_("Selection:");
gchar *s = N_("Time servers");
gchar *s = N_("Select the servers you wish to use for time synchronization.");
gchar *s = N_("_Add");
