/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Time Administration");
gchar *s = N_(":");
gchar *s = N_(":");
gchar *s = N_("Time of day:");
gchar *s = N_("Date/time");
gchar *s = N_("(GMT -1100) Midway Island, Samoa\n"
              "(GMT -1000) Hawaii\n"
              "(GMT -0900) Alaska\n"
              "(GMT -0800) Pacific Time (US & Canada); Tijuana\n"
              "(GMT -0700) Arizona\n"
              "(GMT -0600) Central Time (US & Canada); Mexico City, Tegucigalpa, Saskatchewan\n"
              "(GMT -0500) Eastern Time (US & Canada); Bogota, Lima, Quito\n"
              "(GMT -0400) Atlantic Time (Canada); Caracas, La Paz, Santiago\n"
              "(GMT -0345) Guyana\n"
              "(GMT -0300) Brazil\n"
              "(GMT -0200) Mid-Atlantic\n"
              "(GMT -0100) Azores, Cape Verde Islands\n"
              "(GMT) Casablanca, Monrovia, Dublin, Edinburgh, Lisbon, London\n"
              "(GMT +0100) Amsterdam, Berlin, Bern, Rome, Oslo, Vienna\n"
              "(GMT +0200) Athens, Istanbul, Minsk, Bucharest, Cairo\n"
              "(GMT +0300) Baghdad, Kuwait, Moscow, Volgograd\n"
              "(GMT +0330) Tehran\n"
              "(GMT +0400) Abu Dhabi, Muscat, Baku, Tblisi\n"
              "(GMT +0430) Kabul\n"
              "(GMT +0500) Ekaterinburg, Islamabad, Karachi\n"
              "(GMT +0530) Bombay, Calcutta, Madras, New Delhi\n"
              "(GMT +0600) Astana, Almaty, Dhaka, Colombo\n"
              "(GMT +0630) Rangoon, Kuala Lumpur\n"
              "(GMT +0700) Bangkok, Hanoi, Jakarta\n"
              "(GMT +0800) Singapore, Taipei\n"
              "(GMT +0900) Seoul, Yakutsk\n"
              "(GMT +0930) Adelaide, Darwin\n"
              "(GMT +1000) Brisbane, Canberra, Melbourne, Sydney, Vladivostok\n"
              "(GMT +1100) Magadan, Solomon Islands, New Caledonia\n"
              "(GMT +1200) Auckland, Wellington, Fiji, Kamchatka\n"
              "");
gchar *s = N_("(GMT -1000) Hawaii");
gchar *s = N_("Time zone");
gchar *s = N_("Add");
gchar *s = N_("Keep clock in sync with selected servers");
gchar *s = N_("Time servers");
