/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Time Administration");
gchar *s = N_(":");
gchar *s = N_(":");
gchar *s = N_("Time of day:");
gchar *s = N_("Date/time");
gchar *s = N_("Time zone");
gchar *s = N_("Add");
gchar *s = N_("Keep clock in sync with selected servers");
gchar *s = N_("Time servers");
gchar *s = N_(" Advanced >> ");
