/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("User Settings");
gchar *s = N_("Basic settings");
gchar *s = N_("User name:");
gchar *s = N_("Full Name:");
gchar *s = N_("Advanced settings");
gchar *s = N_("User ID:");
gchar *s = N_("Home directory:");
gchar *s = N_("Shell:");
gchar *s = N_("Basic");
gchar *s = N_("Main group:");
gchar *s = N_("Groups");
gchar *s = N_("Available Groups");
gchar *s = N_("User's Groups");
gchar *s = N_("Add ->");
gchar *s = N_("Remove <-");
gchar *s = N_(" Primary Group ");
gchar *s = N_("label27");
gchar *s = N_("label26");
gchar *s = N_("Groups");
gchar *s = N_("Change Password");
gchar *s = N_("New:");
gchar *s = N_("Confirm:");
gchar *s = N_("  Generate a random password  ");
gchar *s = N_("Check password quality");
gchar *s = N_("Optional Settings");
gchar *s = N_("Maximum days a password may be used:");
gchar *s = N_("Minimum days between password changes:");
gchar *s = N_("Days between warning and password expiration:");
gchar *s = N_("Passwords");
gchar *s = N_("Change Password");
gchar *s = N_("Enter a new password manually, or have one randomly assigned.");
gchar *s = N_("Change Password");
gchar *s = N_("New:");
gchar *s = N_("Confirm:");
gchar *s = N_("  Random Password  ");
gchar *s = N_("Check password quality");
gchar *s = N_("Group Settings");
gchar *s = N_("Group name:");
gchar *s = N_("Members");
gchar *s = N_("All Users");
gchar *s = N_("Group Members");
gchar *s = N_("Add ->");
gchar *s = N_("Remove <-");
gchar *s = N_("label27");
gchar *s = N_("label26");
gchar *s = N_("window1");
gchar *s = N_("This is the list of the users available in the system. Create new users or edit existing user's settings with this dialog.");
gchar *s = N_("Add User...");
gchar *s = N_("Settings...");
gchar *s = N_("Delete");
gchar *s = N_("Users");
gchar *s = N_("Users may be grouped to share resources with others.");
gchar *s = N_("Add Group...");
gchar *s = N_("Settings...");
gchar *s = N_("Delete");
gchar *s = N_("Groups");
gchar *s = N_("These are global values that will affect the creation of new users. They are only available when you click \"More Options\".");
gchar *s = N_("System settings");
gchar *s = N_("Home directory prefix:");
gchar *s = N_("Create home for new users:");
gchar *s = N_("Default shell:");
gchar *s = N_("Min/max values for automatic UID/GID");
gchar *s = N_("Maximum UID:");
gchar *s = N_("Minimum UID:");
gchar *s = N_("Minimum GID:");
gchar *s = N_("Maximum GID:");
gchar *s = N_("Password expiration");
gchar *s = N_("Days a password may be used:");
gchar *s = N_("Minimum days allowed between password changes:");
gchar *s = N_("Days between warning and\n"
              " password expiration:  ");
gchar *s = N_("Minimum  password length:");
gchar *s = N_("Profiles");
gchar *s = N_("Show system users and groups");
gchar *s = N_("window2");
gchar *s = N_("EXPERIMENTAL NIS support.\n"
              "It's only available if You have NIS\n"
              "and when You click on \"More Options\".");
gchar *s = N_("New User");
gchar *s = N_("New Group");
gchar *s = N_("Delete");
gchar *s = N_("Settings for selected user and group");
gchar *s = N_("Change the settings and options for the\n"
              "selected user or group, like a users password\n"
              "or a groups name or members.");
gchar *s = N_("Settings");
gchar *s = N_("label79");
gchar *s = N_("These are global values that will affect the creation of new users. They are only available when you click \"More Options\".");
gchar *s = N_("System settings");
gchar *s = N_("Mailbox directory:");
gchar *s = N_("Create home for new users:");
gchar *s = N_("Min/max values for automatic UID/GID");
gchar *s = N_("Maximum UID:");
gchar *s = N_("Minimum UID:");
gchar *s = N_("Minimum GID:");
gchar *s = N_("Maximum GID:");
gchar *s = N_("Password expiration");
gchar *s = N_("Days a password may be used:");
gchar *s = N_("Minimum days allowed between password changes:");
gchar *s = N_("Days between warning and\n"
              " password expiration:  ");
gchar *s = N_("Minimum  password length:");
gchar *s = N_("label80");
