/* -*- Mode: C; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
#include "text.h"
#include "xst-types.h"
#include "xst-report-hook.h"
#include "xst-report-line.h"
#include "xst-xml.h"
#include "xst-widget.h"
#include "xst-tool.h"
#include "xst-dialog.h"
#include "xst-ui.h"
#include "xst-util.h"
#include "xst-conf.h"
